-- Tabel Profile (Asesi)
create table public.profile (
  id bigint generated by default as identity not null,
  name text not null,
  birth_date date null,
  nik character varying(16) null,
  institusi_id bigint null,
  constraint peserta_baru_pkey primary key (id),
  constraint peserta_baru_name_birth_date_key unique (name, birth_date),
  constraint profile_nik_unique unique (nik),
  constraint fk_profile_institusi foreign KEY (institusi_id) references referensi_institusi (id) on update CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_profile_institusi on public.profile using btree (institusi_id) TABLESPACE pg_default;

-- Tabel Kontak
create table public.kontak (
  id bigint generated by default as identity not null,
  peserta_id bigint not null,
  tipe_kontak character varying(10) not null,
  nilai_kontak text not null,
  constraint kontak_peserta_pkey primary key (id),
  constraint kontak_peserta_unique unique (peserta_id, tipe_kontak, nilai_kontak),
  constraint fk_profile_kontak foreign KEY (peserta_id) references profile (id) on update CASCADE
) TABLESPACE pg_default;

-- Tabel Sertifikat
create table public.sertifikat (
  scheme text null,
  publish date null,
  expires date null,
  name text null,
  id bigint generated by default as identity not null,
  serti_id character varying null,
  peserta_id bigint null,
  constraint sertifikat_test_pkey primary key (id),
  constraint sertifikat_test_id_key unique (id),
  constraint fk_profile_sertifikat foreign KEY (peserta_id) references profile (id) on update CASCADE
) TABLESPACE pg_default;

-- Tabel Perpanjangan Sertifikat
create table public.perpanjangan_sertifikat (
  id bigint generated by default as identity not null,
  peserta_id bigint not null,
  scheme text not null,
  tanggal_ujian date not null,
  created_at timestamp with time zone null default now(),
  constraint perpanjangan_sertifikat_pkey primary key (id),
  constraint perpanjangan_peserta_skema_tanggal_key unique (peserta_id, scheme, tanggal_ujian),
  constraint fk_profile_perpanjangan_cascade foreign KEY (peserta_id) references profile (id) on update CASCADE
) TABLESPACE pg_default;

create index IF not exists idx_perpanjangan_peserta_scheme on public.perpanjangan_sertifikat using btree (peserta_id, scheme) TABLESPACE pg_default;

-- Tabel Referensi Skema
create table public.referensi_skema (
  id bigint generated by default as identity not null,
  nama_skema text not null,
  link_syarat text not null,
  created_at timestamp with time zone null default now(),
  kode_asosiasi text null,
  constraint referensi_skema_pkey primary key (id),
  constraint referensi_skema_nama_skema_key unique (nama_skema),
  constraint fk_referensi_asosiasi foreign KEY (kode_asosiasi) references referensi_asosiasi (kode)
) TABLESPACE pg_default;

create index IF not exists idx_referensi_nama_skema on public.referensi_skema using btree (nama_skema) TABLESPACE pg_default;

-- Tabel Referensi Institusi
create table public.referensi_institusi (
  id bigint generated by default as identity not null,
  nama_institusi text not null,
  kategori text null default 'Non Pasar Modal'::text,
  constraint referensi_institusi_pkey primary key (id),
  constraint referensi_institusi_nama_institusi_key unique (nama_institusi)
) TABLESPACE pg_default;

-- Tabel Referensi Asosiasi
create table public.referensi_asosiasi (
  id bigint generated by default as identity not null,
  kode text not null,
  nama_lengkap text not null,
  link_kontak text not null,
  link_website text not null,
  benefits_html text not null,
  warna_utama text null default '#1565C0'::text,
  warna_bg_box text null default '#f5f5f5'::text,
  warna_border_box text null default '#e0e0e0'::text,
  created_at timestamp with time zone null default now(),
  constraint referensi_asosiasi_pkey primary key (id),
  constraint referensi_asosiasi_kode_key unique (kode)
) TABLESPACE pg_default;
